WildAid/o-fish-realm

WildAidDemo/triggers/recordChangeHistory.json
Disable `recordChangeHistory` until after app import
Fixes #11
=> Disable `recordChangeHistory` until after app import

README.md, WildAidDemo/stitch.json
=> Delay enabling custom user data

CodeForGoodBackup/wildaid/BoardingReports.metadata.json
=> Rogue boardingreport

README.md, WildAidDemo/stitch.json
=> Readme process changes

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Add schema for User collection

WildAidDemo/functions/linkUser/config.json, WildAidDemo/functions/linkUser/source.js, WildAidDemo/triggers/newRealmUser.json
=> Set realmUserID in User doc when new Realm user added

WildAidDemo/triggers/recordChangeHistory.json
=> Make recordChangeHistory trigger events ordered

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Temp - make User.createdOn be a string

WildAidDemo/functions/searchFacetByAgency/config.json, WildAidDemo/functions/searchFacetByAgency/source.js, WildAidDemo/functions/searchFacetByCrews/source.js, WildAidDemo/functions/searchFacetByVessels/source.js
- Actualized functions code due to latest Dev cluster changes.
- searchFacetByVessels
- searchFacetByCrews
=> Actual functions here.

README.md
=> Replace stitch-cli with realm-cli

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Add photo to User schema

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
This was a temporary workaround and can now be removed
Fixes #64
=> Remove DeleteMe role for User collection

WildAidDemo/services/mongodb-atlas/rules/wildaid.MenuData.json
=> Add rules for MenuData collection

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Add "group" sub-document to User schema

WildAidDemo/services/mongodb-atlas/rules/wildaid.Agency.json
=> Add "site" and "email" attributes to Agency schema

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Change photo to be a reference

WildAidDemo/services/mongodb-atlas/rules/wildaid.Photo.json
=> Add schema for Photo collection

WildAidDemo/functions/newPhoto/source.js
=> Use the _id to uniquely identify the S3 file

README.md
=> Remove obsolete Step 17

WildAidDemo/functions/newPhoto/source.js
[-] Clean up sample data
[-] Remove `picture` from `Photo` doc after uploading to S3 (from `newPhoto` function)
fixes #92
=> Fix Photo data

WildAidDemo/auth_providers/anon-user.json
=> Disable anonymous authentication

WildAidDemo/functions/searchFacetByUsers/config.json, WildAidDemo/functions/searchFacetByUsers/source.js
=> Add function to find users

WildAidDemo/functions/newPhoto/source.js
=> Only try uploading picture if it's there

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Allow user to edit their own name

WildAidDemo/functions/isGlobalAdmin/source.js
=> Make isGlobalAdmin more robust to missing "global" attribute

WildAidDemo/services/RealmSync/config.json
=> Remove Realm Sync from import

WildAidDemo/functions/searchFacetByCrews/source.js, WildAidDemo/functions/searchFacetByVessels/source.js
Changed grouping conditions in functions
- searchFacetByVessels
- searchFacetByCrews
=> Faceted search bucket function changed.

README.md
=> Add instructions for creating sync permissions

WildAidDemo/functions/searchFacetByCrews/source.js, WildAidDemo/functions/searchFacetByVessels/source.js
The fixes for "searchFacetByVessel" and "searchFacetByCrew".
=> Current app showing and grouping fixes 

WildAidDemo/functions/isAgencyMember/source.js
=> Search on email/agency name correctly

WildAidDemo/services/RealmSync/rules/wildaid.BoardingReports.json, WildAidDemo/services/mongodb-atlas/rules/wildaid.BoardingReports.json
=> Add a flag to the BoardingReport schema to indicate whether the report is currently a draft

WildAidDemo/services/mongodb-atlas/rules/wildaid.Agency.json
=> Add roles to allow agency admins and officers to access `Agency` docs

WildAidDemo/functions/isPartner/config.json, WildAidDemo/functions/isPartner/source.js, WildAidDemo/services/mongodb-atlas/rules/wildaid.BoardingReports.json
=> Add new partner role and function for BoardingReports

README.md, WildAidDemo/functions/regNewAgency/config.json, WildAidDemo/functions/regNewAgency/source.js
=> Add function to allow anon user to create new User and Agency docs

WildAidDemo/functions/getAgencies/config.json, WildAidDemo/functions/getAgencies/source.js, WildAidDemo/functions/getDashboardStats/config.json, WildAidDemo/functions/getDashboardStats/source.js, WildAidDemo/functions/searchFacetByCrews/source.js, WildAidDemo/functions/searchFacetByVessels/source.js
- 2 new functions
- 3 functions changed
=> Demo 09/22/2020 changes

CONTRIBUTING.md, README.md
- Took away WIP link
- Added documentation links for complex steps
- Moved around some issues to where they make sense (e.g. putting a Search index right after importing the data)
- Removed goals section
=> Adding contributing and updating README

WildAidDemo/functions/regNewAgency/source.js
fixes #149 - @am-MongoDB this should be pushed before we publicize the sandbox.
=> Removing email from Agency description

WildAidDemo/functions/isPartner/source.js, WildAidDemo/services/mongodb-atlas/rules/wildaid.Agency.json, WildAidDemo/services/mongodb-atlas/rules/wildaid.BoardingReports.json
=> Partner agency dates

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
=> adding issue templates

README.md, WildAidDemo/functions/bootStrapDevelopmentAgency/config.json, WildAidDemo/functions/bootStrapDevelopmentAgency/source.js, WildAidDemo/triggers/bootStrapDevelopmentAgency.json, WildAidDemo/values/donorAgency.json
=> Bootstrap new developer agencies

WildAidDemo/services/mongodb-atlas/rules/wildaid.Agency.json, WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Agency share data

WildAidDemo/functions/getAgencies/source.js
=> Added date to match to fix issue #170

WildAidDemo/functions/isPartner/source.js, WildAidDemo/functions/updateInboundPartners/config.json, WildAidDemo/functions/updateInboundPartners/source.js, WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json, WildAidDemo/triggers/AgencyPartnershipChange.json
Fixes #163 
Rules are hard to unit test – issues may be discovered when the web app starts exercising the rules
=> Implement agency-sharing rules

WildAidDemo/functions/isPartner/source.js, WildAidDemo/services/mongodb-atlas/rules/wildaid.Agency.json
=> Fix partner-checking to match web app

WildAidDemo/functions/getAgencies/source.js, WildAidDemo/functions/searchFacetByBoardings/source.js, WildAidDemo/functions/searchFacetByCrews/source.js, WildAidDemo/functions/searchFacetByVessels/source.js
Needed for web changes to work
=> Update functions to filter on agency

WildAidDemo/functions/linkUser/source.js, WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json, WildAidDemo/values/defaultHeadshotImageURL.json
=> Default user headshot

WildAidDemo/functions/getAgencies/source.js
=> Extra checks to avoid indexing into null objects

WildAidDemo/auth_providers/local-userpass.json
Fixes #177 
To accommodate changed in https://github.com/WildAid/o-fish-web/issues/315 and https://github.com/WildAid/o-fish-web/pull/333
=> Add config for password reset using email

WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
=> Add AgencyMember role to User collection

README.md
=> Instructions to set password reset email target

WildAidDemo/functions/searchFacetByBoardings/source.js, WildAidDemo/functions/searchFacetByCrews/source.js, WildAidDemo/functions/searchFacetByVessels/source.js
Getting an error on the Boarding records page (/#/boardings/null) when agenciesToShareData is null, that $in wants an array. So I'm putting in the if statement, that agenciesToShareData has to not be null.
=> updating to account for no shared agencies

WildAidDemo/functions/searchFacetByAgency/source.js
=> Changed officer value to full name of reportingOfficer (concatenated)

WildAidDemo/functions/isPartner/source.js, WildAidDemo/services/mongodb-atlas/rules/wildaid.Agency.json
=> Allow multiple date ranges for agency sharing

WildAidDemo/auth_providers/local-userpass.json, WildAidDemo/functions/getDashboardTime/config.json, WildAidDemo/functions/getDashboardTime/source.js, WildAidDemo/services/mongodb-atlas/rules/wildaid.DutyChange.json, WildAidDemo/services/mongodb-atlas/rules/wildaid.MenuData.json, WildAidDemo/services/mongodb-atlas/rules/wildaid.User.json
https://github.com/WildAid/o-fish-web/issues/230
Also changed:
- better password reset subject, since the email has mongodb branding, I wanted to put O-FISH in there.
- fixed typos in rules for User because
Fixes #
=> Added getDashboardTime and DutyChange schema for https://github.com/WildAid/o-fish-web/issues/230

WildAidDemo/functions/searchFacetByBoardings/source.js
the aggregate pipeline was broken, as `aggregateTerms` - which contains `$search` - was placed after `agencyAggregate`.
Which caused the following error:
```
"(Location40602) $_internalSearchMongotRemote is only valid as the first stage in a pipeline.
uncaught promise rejection: (Location40602) $_internalSearchMongotRemote is only valid as the first stage in a pipeline."
```
Swapping them around placed the `$search` first, and fixed the issue
Fixes #200
I have tested the changes in my clone of the environment, which works as expected.
=> Fix: aggregation pipeline to call $search first

WildAidDemo/functions/search/source.js
=> Return empty results if the query string is empty

WildAidDemo/functions/searchFacetByBoardings/source.js
=> sort by boarding order

WildAidDemo/functions/searchFacetByBoardings/source.js
=> Risk Filter functionality
